const data = [
  {
    id: 0,
    image: "./photos/0.JPG",
    title: "Wings wide open",
    desc: "Wouldn't it be beautiful to be able to fly as a bird? - to fly above cities, countries, oceans..., to feel that there’re no boundaries and you can fly wherever you want. Birds are beautiful, they inspire freedom. When you look at birds you realize how chained you are to your body. Just imagine flying and being carried by the wind's waves…",
    category: "freedom",
  },
  {
    id: 1,
    image: "./photos/1.JPG",
    title: "The Discussion",
    desc: "I’ve always found a strange interest for empty benches. To me, it seems that they are not just inviting you to sit, but also to reflect and to take silence as your companion. ",
    category: "silence",
  },
  {
    id: 2,
    image: "./photos/2.JPG",
    title: "Apollo and me",
    desc: "That’s my bike Apollo. One of my good friends gave it its name - ,,It will take you to the moon”, told me my friend the day I bought the bike. And he was not exaggerating – riding my bike gave me so many unchained feelings.",
    category: "silence",
  },
  {
    id: 3,
    image: "./photos/3.JPG",
    title: "The only bird in the sky",
    desc: "Wouldn't it be beautiful to be able to fly as a bird? - to fly above cities, countries, oceans..., to feel that there’re no boundaries and you can fly wherever you want. Birds are beautiful, they inspire freedom. When you look at birds you realize how chained you are to your body. Just imagine flying and being carried by the wind's waves…",
    category: "freedom",
  },
  {
    id: 4,
    image: "./photos/4.JPG",
    title: "A sky of birds",
    desc: "Every autumn and winter evening, for some minutes, the sky is full of ravens. Where are they flying? It seems as they are afraid of something and are flying to a safer place. And how loud they are croaking... Croaking a raven symphony! In these minutes, it’s all about the ravens… - about their flight and about their symphony. ",
    category: "freedom",
  },
  {
    id: 5,
    image: "./photos/5.JPG",
    title: "The Drops of freezing rain",
    desc: "Drops, drops, drops... It was a cold and beautiful winter night. Through the street light, you could capture for a glince of a moment the frozen drops of winter.",

    category: "silence",
  },
  {
    id: 6,
    image: "./photos/6.JPG",
    title: "The Birds are always there",
    desc: "It was a quick shot. I focused instinctively the camera and pressed the button. After developing the film, I was happy to see that the photo is much better than I thought.",

    category: "nature",
  },
  {
    id: 7,
    image: "./photos/7.JPG",
    title: "The Steps into the forest's shadoow",
    desc: "",
    category: "peace",
  },
  {
    id: 8,
    image: "./photos/8.JPG",
    title: "I see myself better in reflection",
    desc: "",
    category: "silence",
  },
  {
    id: 9,
    image: "./photos/9.JPG",
    title: "The tree, the hills, the sky",
    desc: "",
    category: "peace",
  },
  {
    id: 10,
    image: "./photos/10.JPG",
    title: "The umbrella and the rained path",
    desc: "It was a raining day. ",
    category: "peace",
  },
  {
    id: 11,
    image: "./photos/11.JPG",
    title: "The ocean's wind",
    desc: "I had 10 seconds to run and position myself in front of the camera: the timer is set; the button is pressed and I’m standing and waiting for the shoot. The camera’s lens wink and I can move on and discover the shore.",
    category: "freedom",
  },
  {
    id: 12,
    image: "./photos/12.JPG",
    title: "The water will cover the shore",
    desc: "",
    category: "nature",
  },
  {
    id: 13,
    image: "./photos/13.JPG",
    title: "The Wild trees",
    desc: "",
    category: "nature",
  },
  {
    id: 14,
    image: "./photos/14.JPG",
    title: "The Atlantic Ocean",
    desc: "It was for the first time when I saw the Atlantic Ocean. I was looking in the void of the horizon – I felt my pettiness in front of the ocean’s boundlessness.",
    category: "nature",
  },
  {
    id: 15,
    image: "./photos/15.JPG",
    title: "Have you seen the water?",
    desc: "",
    category: "nature",
  },
  {
    id: 16,
    image: "./photos/16.JPG",
    title: "The company of a curly tree ",
    desc: "",
    category: "silence",
  },
  {
    id: 17,
    image: "./photos/17.JPG",
    title: "Fusion of Winter and Summer",
    desc: "Half step in the winter, half step in the summer.",
    category: "nature",
  },
  {
    id: 18,
    image: "./photos/18.JPG",
    title: "The Student's Church",
    desc: "",
    category: "silence",
  },
  {
    id: 19,
    image: "./photos/19.JPG",
    title: "The sleeping city",
    desc: "",
    category: "silence",
  },
];

export default data;
